{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator-autoconfigure",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "size": 750256,
          "sha512": "93970191a9b75ce22baa9f3405f5676895b3ff5c05225eb9a26628d9eebd566d47dcaaeb98730ee382d2146c5791e815c5992613dc75bff9241399056710f044",
          "sha256": "201b4f6c392037fe9f6cce4de036273a23d944f0ad5025f21eadcc66fb0ef29e",
          "sha1": "c2ecd7cb4880408ba131c14fe6521c8c28790bb6",
          "md5": "2decf02169dc612d0a17f59553bca1b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.15.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "size": 750256,
          "sha512": "93970191a9b75ce22baa9f3405f5676895b3ff5c05225eb9a26628d9eebd566d47dcaaeb98730ee382d2146c5791e815c5992613dc75bff9241399056710f044",
          "sha256": "201b4f6c392037fe9f6cce4de036273a23d944f0ad5025f21eadcc66fb0ef29e",
          "sha1": "c2ecd7cb4880408ba131c14fe6521c8c28790bb6",
          "md5": "2decf02169dc612d0a17f59553bca1b3"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "size": 750256,
          "sha512": "93970191a9b75ce22baa9f3405f5676895b3ff5c05225eb9a26628d9eebd566d47dcaaeb98730ee382d2146c5791e815c5992613dc75bff9241399056710f044",
          "sha256": "201b4f6c392037fe9f6cce4de036273a23d944f0ad5025f21eadcc66fb0ef29e",
          "sha1": "c2ecd7cb4880408ba131c14fe6521c8c28790bb6",
          "md5": "2decf02169dc612d0a17f59553bca1b3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-autoconfigure-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.2.jar",
          "size": 750256,
          "sha512": "93970191a9b75ce22baa9f3405f5676895b3ff5c05225eb9a26628d9eebd566d47dcaaeb98730ee382d2146c5791e815c5992613dc75bff9241399056710f044",
          "sha256": "201b4f6c392037fe9f6cce4de036273a23d944f0ad5025f21eadcc66fb0ef29e",
          "sha1": "c2ecd7cb4880408ba131c14fe6521c8c28790bb6",
          "md5": "2decf02169dc612d0a17f59553bca1b3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-actuator-autoconfigure-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.2-javadoc.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.2-javadoc.jar",
          "size": 1337960,
          "sha512": "189796c9f10072146c4eb8a12f8e9019d61304a9e2abc415cdd39786221aa836a0aad82d2ee8db4f491a9bfd80a71b9bb07eac6d4090c18d88f97e5a71191fc8",
          "sha256": "775fe46f6a699bd313b4112c327a316f00ac823ced75e263cb41eada88b0850a",
          "sha1": "83d472b9c7b0548a8f97f73a0c087efc9b3706c1",
          "md5": "9f1b53fb027c5deab7e75e6d439c0876"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-autoconfigure-3.2.2-sources.jar",
          "url": "spring-boot-actuator-autoconfigure-3.2.2-sources.jar",
          "size": 533906,
          "sha512": "a310ef450b30e870420893f995265d3761467dc78012ad849a9fdf18c35d8ff7aeeb2c72ac0bf2e76f8f543d3460bd2f4d487c093146ac067c55053d382fcf1e",
          "sha256": "70a47350059c331be7fa247e45a9168bce566d90e6c1ef3cdc2227aa07e20484",
          "sha1": "fa583fc0ec53f47f7f2e23de5b7c7f194baf1d1d",
          "md5": "dffe20cf96564b57eaef7832d21427ea"
        }
      ]
    }
  ]
}
