{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "3.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.2.jar",
          "url": "spring-boot-starter-actuator-3.2.2.jar",
          "size": 4805,
          "sha512": "480d229c7af558af848300bd3d2b548d89f4673a16d8dd996a851883c180f457e17cc2df62a0a2b3ee20161711dcbd3a7cc785a7dc0da15324e7ef3fa73f349b",
          "sha256": "f4358ca73f92eb9b76d458ec065195564342a5d0a89ce33ece06adfca256f3af",
          "sha1": "bb329cb8813ad75e76baad30658b756f57c8f6fb",
          "md5": "9fdb5b9cba99c39cf680670459fbff89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.2.jar",
          "url": "spring-boot-starter-actuator-3.2.2.jar",
          "size": 4805,
          "sha512": "480d229c7af558af848300bd3d2b548d89f4673a16d8dd996a851883c180f457e17cc2df62a0a2b3ee20161711dcbd3a7cc785a7dc0da15324e7ef3fa73f349b",
          "sha256": "f4358ca73f92eb9b76d458ec065195564342a5d0a89ce33ece06adfca256f3af",
          "sha1": "bb329cb8813ad75e76baad30658b756f57c8f6fb",
          "md5": "9fdb5b9cba99c39cf680670459fbff89"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.2.jar",
          "url": "spring-boot-starter-actuator-3.2.2.jar",
          "size": 4805,
          "sha512": "480d229c7af558af848300bd3d2b548d89f4673a16d8dd996a851883c180f457e17cc2df62a0a2b3ee20161711dcbd3a7cc785a7dc0da15324e7ef3fa73f349b",
          "sha256": "f4358ca73f92eb9b76d458ec065195564342a5d0a89ce33ece06adfca256f3af",
          "sha1": "bb329cb8813ad75e76baad30658b756f57c8f6fb",
          "md5": "9fdb5b9cba99c39cf680670459fbff89"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.2.jar",
          "url": "spring-boot-starter-actuator-3.2.2.jar",
          "size": 4805,
          "sha512": "480d229c7af558af848300bd3d2b548d89f4673a16d8dd996a851883c180f457e17cc2df62a0a2b3ee20161711dcbd3a7cc785a7dc0da15324e7ef3fa73f349b",
          "sha256": "f4358ca73f92eb9b76d458ec065195564342a5d0a89ce33ece06adfca256f3af",
          "sha1": "bb329cb8813ad75e76baad30658b756f57c8f6fb",
          "md5": "9fdb5b9cba99c39cf680670459fbff89"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-actuator-maven-optional",
          "version": "3.2.2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.2-javadoc.jar",
          "url": "spring-boot-starter-actuator-3.2.2-javadoc.jar",
          "size": 4744,
          "sha512": "9404efa6f89683716c87b67a314f6e07c903a6a773bbe66d4274a0a69f3b83d1d7869a90e00e49e85c12a9b48a780eab6b290cf6abedf6706364b89c76c7d456",
          "sha256": "e719428a819c475cbef2307d2aa5a87b5c0b6d78c26dd85d0f2eee7f9c371e90",
          "sha1": "5eb96c0cb491771f94eceaf15899de7d9096cf89",
          "md5": "d73a01552fbce8acccded317de49d92a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.2.2-sources.jar",
          "url": "spring-boot-starter-actuator-3.2.2-sources.jar",
          "size": 4743,
          "sha512": "7f0932bb7d8063afcaecd234f683785c07e6277c12ebe0864bad1a890c634d86b9d4ddd924896b894e4e80cea401cdeb02044cc88e0e84bc44e1d9e58991e204",
          "sha256": "62f9e7439b03ecc5776b6616322aa640f8dc509081053afcdb4457d635c71028",
          "sha1": "ad83e72e9b7124417806d0133caa888d8461f31d",
          "md5": "cd2a78c7e45555bdbaa059acc563bb95"
        }
      ]
    }
  ]
}
